# Generated by Django 6.1.1 on 2026-09-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('device_id', models.IntegerField(help_text='ID, который отправляет ESP32 (уникальный для каждой платы)', unique=True, verbose_name='ID устройства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последний сигнал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='plants.plant', verbose_name='Привязанное растение')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
