# Generated by Django 6.1.1 on 2026-09-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False, verbose_name='Камера включена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Состояние камеры',
                'verbose_name_plural': 'Состояния камеры',
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic', models.BooleanField(default=True, verbose_name='Автоматический режим')),
                ('pump', models.BooleanField(default=False, verbose_name='Полив включён')),
                ('light', models.BooleanField(default=False, verbose_name='Свет включён')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние устройства',
                'verbose_name_plural': 'Состояния устройств',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('min_humidity', models.IntegerField(default=30, verbose_name='Нижний порог влажности %')),
                ('max_humidity', models.IntegerField(default=70, verbose_name='Верхний порог влажности %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(verbose_name='Влажность почвы %')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура °C')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Показание датчика',
                'verbose_name_plural': 'Показания датчиков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=5, verbose_name='Длительность (секунд)')),
                ('source', models.CharField(choices=[('auto', 'Автоматический'), ('manual', 'Ручной (сайт)')], default='auto', max_length=20, verbose_name='Источник')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('start_watering_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время начала')),
                ('end_watering_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время окончания')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_logs', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Лог полива',
                'verbose_name_plural': 'Логи поливов',
                'ordering': ['-started_at'],
            },
        ),
    ]
