# Generated by Django 6.1.1 on 2026-09-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
    ]
