# Generated by Django 6.1.1 on 2026-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic', models.BooleanField(default=True, verbose_name='Автоматический режим')),
                ('pump', models.BooleanField(default=False, verbose_name='Полив включён')),
                ('light', models.BooleanField(default=False, verbose_name='Свет включён')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние устройства',
                'verbose_name_plural': 'Состояния устройств',
            },
        ),
    ]
