# Generated by Django 6.1.1 on 2026-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_devicestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False, verbose_name='Камера включена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Состояние камеры',
                'verbose_name_plural': 'Состояния камеры',
            },
        ),
    ]
