# Generated by Django 6.1.1 on 2026-09-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_camerastate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringlog',
            name='end_watering_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='wateringlog',
            name='start_watering_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='source',
            field=models.CharField(choices=[('auto', 'Автоматический'), ('manual', 'Ручной (сайт)')], default='auto', max_length=20, verbose_name='Источник'),
        ),
    ]
